security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#the-firewall

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    # Encoders, providers, firewalls, etc.
    # ...

    access_control:
        # Routes publiques
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }

        # ROLE_STUDENT (Alternant)
        - { path: ^/calendar-schedule, roles: ROLE_STUDENT }
        - { path: ^/evaluations/student, roles: ROLE_STUDENT }
        - { path: ^/teaching-team-list, roles: ROLE_STUDENT }

        # ROLE_TUTOR (Tuteur)
        - { path: ^/evaluations/tutor, roles: ROLE_TUTOR }
        - { path: ^/evaluation/tutor, roles: ROLE_TUTOR }

        # ROLE_TTM (Membre de l'équipe pédagogique)
        - { path: ^/evaluations/ttm, roles: ROLE_TTM }
        - { path: ^/evaluation/ttm, roles: ROLE_TTM }
        - { path: ^/behavior, roles: ROLE_TTM }
        - { path: ^/behavior-manage, roles: ROLE_TTM }
        - { path: ^/skill-manage, roles: ROLE_TTM }
        - { path: ^/classroom, roles: ROLE_TTM }
        - { path: ^/school-year, roles: ROLE_TTM }
        - { path: ^/period, roles: ROLE_TTM }
        - { path: ^/users, roles: ROLE_TTM }
        - { path: ^/diploma, roles: ROLE_TTM }
        - { path: ^/formation-center, roles: ROLE_TTM }
        - { path: ^/establishment, roles: ROLE_TTM }


        # multiples roles
        - { path: ^/evaluation-visualizer, roles: [ROLE_TTM, ROLE_PT] }
        - { path: ^/export-evaluations, roles: [ROLE_TTM, ROLE_PT] }

        # ROLE_ADMIN

        # ROLE_SUPER_ADMIN
        - { path: ^/super-admin, roles: ROLE_SUPER_ADMIN }

        # Toutes les autres routes nécessitent un utilisateur connecté
        - { path: ^/, roles: ROLE_USER }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            # By default, password hashers are resource intensive and take time. This is
            # important to generate secure password hashes. In tests however, secure hashes
            # are not important, waste resources and increase test times. The following
            # reduces the work factor to the lowest possible values.
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
